SELECT C.NAME, COUNT(S.NAME) AS STUDENTS FROM STUDENT S INNER JOIN PLACEMENTS P ON S.ID=P.S_ID RIGHT JOIN COMPANY C ON C.ID=P.C_ID GROUP BY C.NAME;

SELECT "SEPTEMBER", NAME AS COMPANY FROM COMPANY WHERE `INTERVIEW DATE`
LIKE '2020-09-%';

SELECT NAME AS COMPANY, `INTERVIEW DATE` AS DATE FROM COMPANY WHERE `INTERVIEW DATE` <= CURRENT_TIMESTAMP();

SELECT S.NAME AS STUDENT, C.NAME AS COMPANY FROM COMPANY C INNER JOIN PLACEMENTS P ON P.C_ID=C.ID INNER JOIN STUDENT S ON S.ID=P.S_ID WHERE P.S_ID IN (SELECT S_ID FROM PLACEMENTS GROUP BY S_ID HAVING COUNT(S_ID)>1);

SELECT S.NAME AS NAME, C.DEPT AS DEPARTMENT, S.CGPA AS CGPA FROM STUDENT S INNER JOIN PLACEMENTS P ON S.ID=P.S_ID WHERE S.CGPA>7.0 AND P.S_ID NOT IN (SELECT S_ID FROM PLACEMENTS GROUP BY S_ID HAVING COUNT(S_ID)>=1);

SELECT S.NAME AS NAME, S.DEPT AS DEPARTMENT, S.CGPA AS CGPA FROM STUDENT S WHERE S.ID NOT IN (SELECT S_ID FROM PLACEMENTS GROUP BY S_ID HAVING COUNT(S_ID
)>=1);

SELECT NAME AS COMPANY, LOCATION FROM COMPANY WHERE LOCATION LIKE 'B%'; 
